import {StyleSheet} from 'react-native';
import {horizontalScale, verticalScale} from '../../utils/dimension';
const HomePageStyle = StyleSheet.create({
  Container: {flex: 1, flexDirection: 'column', backgroundColor: '#FFFFFF'},
  Content: {
    flexDirection: 'column',
    marginLeft: 3,
    marginTop: 10,
  },
  ContainerCard: {
    marginTop: 10,
    backgroundColor: '#1A73E9E0',
    flexDirection: 'row',
    width: horizontalScale(320),
    height: verticalScale(188),
    marginLeft: 30,
    marginRight: 20,
    borderRadius: 5,
    shadowOpacity: 56,
  },
  TextCardNumber: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    top: 20,
    left: 10,
  },
  TextValCardNumber: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    top: 21,
    left: 10,
  },
  TextCardSaldo: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 18,
    top: 35,
    left: 10,
  },
  TextValSaldo: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 19,
    top: 34,
    left: 10,
  },
  TextElectricalUsage: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    top: 19,
  },
  TextValElectricalUsage: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 19,
    top: 19,
  },
  TextDeviceTemp: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    top: 30,
  },
  TextValDeviceTemp: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 19,
    top: 30,
  },
  TextDeviceStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    top: 35,
  },
  TextValDeviceStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 19,
    top: 34,
  },
});

export default HomePageStyle;
