import {StyleSheet} from 'react-native';

const IotMonitoringStyle = StyleSheet.create({
  Container: {
    flex: 1,
    flexDirection: 'column',
    backgroundColor: '#FFFFFF',
  },
  ContentContainer: {flexDirection: 'column', left: 3, top: 10},
  DeviceCardContainer: {
    top: 5,
    backgroundColor: '#1A73E9E0',
    flexDirection: 'row',
    width: 320,
    height: 188,
    borderRadius: 5,
    shadowOpacity: 56,
    alignSelf: 'center',
  },
  DataUsageContainer: {
    flexDirection: 'column',
    top: 25,
    left: 15,
    alignItems: 'center',
  },
  ContainerDeviceDetail: {flexDirection: 'column', left: 25, top: 10},
  TextDeviceId: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
  },
  TextValueDeviceId: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    maxWidth: 160,
  },
  TextDeviceStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    top: 10,
  },
  TextValueDeviceStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    maxWidth: 160,
    top: 10,
  },
  TextSignalStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    top: 16,
  },
  TextValueSignalStatus: {
    color: '#FFFFFF',
    fontFamily: 'Roboto',
    fontStyle: 'normal',
    fontWeight: '700',
    fontSize: 14,
    maxWidth: 160,
    top: 16,
  },
  SensorGaugeContainer: {
    top: 40,
    flexDirection: 'column',
    width: 320,
    height: 188,
    borderRadius: 5,
    shadowOpacity: 56,
    alignSelf: 'center',
  },
  CardNetworkDetailContainer: {
    top: 55,
    flexDirection: 'column',
    width: 320,
    height: 188,
    borderRadius: 5,
    shadowOpacity: 56,
    alignSelf: 'center',
  },
  ActivityIndicator: {
    top: 10,
    textAlign: 'center',
    fontFamily: 'Roboto',
    height: 24,
    fontSize: 14,
    fontWeight: '500',
    fontStyle: 'normal',
  },
});
export default IotMonitoringStyle;
