const PUBLIC_BASE_URL = 'http://37.44.244.196:2022/';

// PATH
const REGISTER_PATH = PUBLIC_BASE_URL + 'user/register';
const AUTH_USER_PATH = PUBLIC_BASE_URL + 'user/';

// action type
const PROCESS_REGISTER_USER = 'PROCESS_REGISTER_USER';
const FAILED_REGISTER_USER = 'FAILED_REGISTER_USER';
const HIDE_ALERT = 'HIDE_ALERT';
const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER';

const PROCESS_LOGIN_USER = 'PROCESS_LOGIN_USER';
const SUCCESS_LOGIN_USER = 'SUCCESS_LOGIN_USER';

// action get device pair
const PROCESS_GET_DEVICE_PAIR = 'PROCESS_GET_DEVICE_PAIR';
const SUCCESS_GET_DEVICE_PAIR = 'SUCCESS_GET_DEVICE_PAIR';
const FAILED_GET_DEVICE_PAIR = 'FAILED_GET_DEVICE_PAIR';

export {
  PUBLIC_BASE_URL,
  REGISTER_PATH,
  PROCESS_REGISTER_USER,
  FAILED_REGISTER_USER,
  HIDE_ALERT,
  SUCCESS_REGISTER_USER,
  PROCESS_LOGIN_USER,
  AUTH_USER_PATH,
  SUCCESS_LOGIN_USER,
  PROCESS_GET_DEVICE_PAIR,
  SUCCESS_GET_DEVICE_PAIR,
  FAILED_GET_DEVICE_PAIR,
};
