const PUBLIC_BASE_URL = 'http://37.44.244.196:2022/';

// PATH
const REGISTER_PATH = PUBLIC_BASE_URL + 'user/register';

// action type
const PROCESS_REGISTER_USER = 'PROCESS_REGISTER_USER';
const FAILED_REGISTER_USER = 'FAILED_REGISTER_USER';
const HIDE_ALERT = 'HIDE_ALERT';
const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER';
export {
  PUBLIC_BASE_URL,
  REGISTER_PATH,
  PROCESS_REGISTER_USER,
  FAILED_REGISTER_USER,
  HIDE_ALERT,
  SUCCESS_REGISTER_USER,
};
